### ISSUE TITLE
jhipster-dotnet on sonarCloud and Sample Repository on github

### ISSUE THREAD

**Issue by UgoWithoutH** [jhipster/jhipster-dotnet#10]
**Overview of the issue**

Create jhipster-dotnet on Sonarcloud And create a Repository for Sample on Github

**Comment by pascalgrimaud** [comment]
Thanks, will try to do it after my day work

**Comment by pascalgrimaud** [comment]
The repository for sample is already created, few days ago:
https://github.com/jhipster/jhipster-dotnet-sample

**Comment by pascalgrimaud** [comment]
The project has been created at [sonarcloud](https://sonarcloud.io/organizations/jhipster/projects)

![image](https://user-images.githubusercontent.com/9156882/170083083-15aa121a-de16-46f8-8696-9a6b2868c9c1.png)

And the SONAR_TOKEN has been added too:

![image](https://user-images.githubusercontent.com/9156882/170083229-f83be310-3e0e-4997-a95d-9c06576e015b.png)

**Comment by pascalgrimaud** [comment]
@UgoWithoutH : now you need to work on the GitHub Actions to push the Sonar Analysis
Don't hesitate to ping me if I miss something

**Comment by nicolas63** [comment]
Thanks @pascalgrimaud can you also do this for the sample repository please ?

**Comment by pascalgrimaud** [comment]
done too:

![image](https://user-images.githubusercontent.com/9156882/170084562-b6fd021d-27bf-416e-abf5-11fbb52c3bd0.png)
